on: [push]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Matrix Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Test code
      env:
        GO111MODULE: on
      run: ./scripts/test_all.sh
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go 1.13.1
      uses: actions/setup-go@v1
      with:
        go-version: '1.13.1'
    - name: Checkout code
      uses: actions/checkout@v1        
    - name: Build TUSD
      env:
        GO111MODULE: on
      run: ./scripts/build_all.sh    